---
resources:
- name: postfacto-deployment
  type: git
  source: {uri: "https://github.com/bosh-rebels/postfacto-deployment.git"}

jobs:
- name: job
  public: true
  plan:
  - get: postfacto-deployment
  - task: package
    file: postfacto-deployment/tasks/package.yml
  - task: deploy
    file: postfacto-deployment/tasks/deploy.yml
    params:
      ADMIN_EMAIL: ((admin_email))
      ADMIN_PASSWORD: ((admin_password))
      APP_NAME: ((app_name))
      ENABLE_ANALYTICS: false
