platform: linux

image_resource:
  type: docker-image
  source: 
    repository: registry-ukdev01.paas.santanderuk.dev.corp/paymentshubpcf/postfacto
    tag: 'v1'
    username: ((harbor_username))
    password: ((harbor_password))
    insecure_registries: ["registry-ukdev01.paas.santanderuk.dev.corp"]

inputs:
  - name: postfacto-deployment

params:
  ADMIN_EMAIL:
  ADMIN_PASSWORD:
  APP_NAME:
  ENABLE_ANALYTICS:

run:
  path: postfacto-deployment/tasks/deploy.sh
